### PR TITLE
Add a .gitignore

### PR DESCRIPTION
**Pull request by ankushagarwal**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/22)

### CODE REVIEW

**Comment by texasmichelle** [comment]
Could you add a few more lines? I used the .gitignore from kubeflow/kubeflow as a starting point and we might not need everything in there, but it's a bit more robust. This is the one I've been using in a different PR: https://github.com/texasmichelle/examples/blob/master/.gitignore

**Comment by ankushagarwal** [comment]
Added

**Comment by ankushagarwal** [comment]
@texasmichelle Can you merge this? I don't think I have the permissions.

**Comment by texasmichelle** [comment]
Ignoring unrelated presubmit tests since they were be resolved by [PR-18](https://github.com/kubeflow/examples/pull/18).

**Pull request merged**
