### PR TITLE
Example workflow for Github issue summarization. 

### PR DESCRIPTION
**Pull request by vicaire**
This is a very rough Argo workflow for Github issue summarization. Some details:

- For now, the workflow assumes the use of GCS, GKE, and the GCP container registry. 
- The prediction and recommendation steps just print results in the logs. This should be replaced by a microservice serving recommendations. 
- I tested end-to-end using a small amount of data as described in the README.md. To run the workflow with more data, the GKE cluster must use larger VMs. 
- This summarization is entirely based on the blog post by Hamel Husain (https://towardsdatascience.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8) 
- The workflow uses a volume to pass output data from one container to another. The results are backed up in GCS.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/35)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Thanks! This looks really neat. I have one minor comment. LGTM otherwise.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[github_issue_summarization/workflow/github_issues_summarization.yaml, line 108 at r1](https://reviewable.io:443/reviews/kubeflow/examples/35#-L764jafWyOU2rm_9LcX:-L764jafWyOU2rm_9LcY:b-cwypn0) ([raw file](https://github.com/kubeflow/examples/blob/10a8506b1e3bfe0d14c67d8ad072084c4cab7322/github_issue_summarization/workflow/github_issues_summarization.yaml#L108)):*
> ```YAML
>       image: "{{workflow.parameters.container-image}}"
>       command: [sh, -c]
>       args: ["cd ./workspace/src; python process_data.py --input_csv=/mnt/workspace/data/github_issues_medium.csv --sample_size={{workflow.parameters.sample-size}} --output_traindf_csv=/mnt/workspace/data/github_issues_medium_train.csv --output_testdf_csv=/mnt/workspace/data/github_issues_medium_test.csv"]
> ```

nit: Can you use `source: ` instead of `args:` to pass your scripts. That might make this easier to read

Examples are here: https://github.com/argoproj/argo/tree/master/examples#scripts--results

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/35#-:-L765_dWVhrmfJcZwZob:bxhvyi3)*

**Comment by vicaire** [comment]
Thanks Ankush. 

I just tried to use 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[github_issue_summarization/workflow/github_issues_summarization.yaml, line 108 at r1](https://reviewable.io:443/reviews/kubeflow/examples/35#-L764jafWyOU2rm_9LcX:-L76xbVxik0aoW2QLDo0:b2qd8t4) ([raw file](https://github.com/kubeflow/examples/blob/10a8506b1e3bfe0d14c67d8ad072084c4cab7322/github_issue_summarization/workflow/github_issues_summarization.yaml#L108)):*
<details><summary><i>Previously, ankushagarwal (Ankush Agarwal) wrote…</i></summary><blockquote>

nit: Can you use `source: ` instead of `args:` to pass your scripts. That might make this easier to read

Examples are here: https://github.com/argoproj/argo/tree/master/examples#scripts--results
</blockquote></details>

Thanks Ankush. 

I just tried to use script/source. 

Unfortunately, it seems that volume mounting does not work when using script/source. 

I checked the Argo repo and it seems that the feature is not available in Argo 2.0:

https://github.com/argoproj/argo/commit/491ed08ffe2f8430fcf35bf36e6dd16707eb5a0a#diff-9ce7ea8441086bf1902b4f936f4601d0R402

It was added in Argo 2.1:

https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json#L525

But Argo does not yet provide a release for 2.1 in the installation instructions: 

https://github.com/argoproj/argo/blob/master/demo.md

Let me know how you would like to proceed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/35#-:-L76xjSFK8kIdf0kbq56:bw18bvf)*

**Comment by ankushagarwal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[github_issue_summarization/workflow/github_issues_summarization.yaml, line 108 at r1](https://reviewable.io:443/reviews/kubeflow/examples/35#-L764jafWyOU2rm_9LcX:-L77257muG2v5lfmvZ9H:b4t5sv0) ([raw file](https://github.com/kubeflow/examples/blob/10a8506b1e3bfe0d14c67d8ad072084c4cab7322/github_issue_summarization/workflow/github_issues_summarization.yaml#L108)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

Thanks Ankush. 

I just tried to use script/source. 

Unfortunately, it seems that volume mounting does not work when using script/source. 

I checked the Argo repo and it seems that the feature is not available in Argo 2.0:

https://github.com/argoproj/argo/commit/491ed08ffe2f8430fcf35bf36e6dd16707eb5a0a#diff-9ce7ea8441086bf1902b4f936f4601d0R402

It was added in Argo 2.1:

https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json#L525

But Argo does not yet provide a release for 2.1 in the installation instructions: 

https://github.com/argoproj/argo/blob/master/demo.md

Let me know how you would like to proceed. 

</blockquote></details>

I guess args is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/35)*

**Pull request merged**
