### PR TITLE
minst example - Add Azure instructions / update Argo package

### PR DESCRIPTION
**Pull request by julienstroheker**
* Update the labs for Azure Users
* Using the last release of Argo

cc @sozercan @ritazh

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/114)

### CODE REVIEW

**Comment by DjangoPeng** [comment]
LGTM 

@jlewi @ddysher Would like to take a look?

**Comment by julienstroheker** [comment]
@djangopeng @jlewi @ddysher any news on this? Thanks.

**Comment by ddysher** [comment]
LGTM

ping @jlewi

**Comment by texasmichelle** [comment]
Thanks for the azure update @julienstroheker!

**Pull request merged**
