### PR TITLE
Update Training.ipynb

### PR DESCRIPTION
**Pull request by hamelsmu**
Added Model Evaluation.  Deleted Table of Contents because you need Jupyter Extension to update that, so not worth it.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/52)

### CODE REVIEW

**Comment by hamelsmu** [comment]
FYI @jlewi @texasmichelle

**Comment by texasmichelle** [comment]
Great addition to the notebook!
/lgtm

**Pull request merged**
