### PR TITLE
Add testing for xgboost_synthetic

### PR DESCRIPTION
**Pull request by jinchihe**
fixes: #620

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/633)

### CODE REVIEW

**Comment by jinchihe** [comment]
Seems need to upgrade python in the tester image, or build new image for the testing.
```
kfp requires Python '>=3.5.3' but the running Python is 3.5.2
```

**Comment by jinchihe** [comment]
Need upgrade tornado, but that's strange, does not work after upgraded from pip, update the requirement.txt file to upgrade.

```
---> 37 from tornado.util import ObjectDict, PY3, unicode_type
    38
    39 if PY3:
ImportError: cannot import name 'PY3'
```

**Comment by jinchihe** [comment]
Seems need more effort than I estimated, hit some problems while executing notebook...

**Comment by jinchihe** [comment]
Got another problem, seems we need to create role and RoleBinding for this?
```
ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '57565ba8-a235-44d1-aee8-5b8b75ad8e50', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 10 Sep 2019 10:29:34 GMT', 'Content-Length': '344'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:xgboost-synthetic-1171365094769037312:default\" cannot create resource \"pods\" in API group \"\" in the namespace \"xgboost-synthetic-1171365094769037312\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

**Comment by jinchihe** [comment]
/assign @jlewi 

Hello @jlewi , the PR is ready for review now, could you please take a look?

The efforts for the changes are greater than I estimated, from initial thoughts, just create one step to execute notebook, but really fall into some problems while executing notebook, such as #634 https://github.com/kubeflow/fairing/issues/367 https://github.com/kubeflow/fairing/issues/361 etc... Tooked big efforts to investigation and try to work aroud those porblem. But finally I get that by creating a build image steps, and submmit execute steps to test cluster... For now, we get that, the test works fine now.

@jlewi by the way, I keep use old ci/cd ways (`ks`) to create the testing since I found all tests in example use `ks` way. I suggest to check in with this way firstly, I may investigate and update all examples presummit tests to `py_func` together after China Mid-Autumn Festival. Thanks!

**Comment by jlewi** [comment]
Thanks @jinchihe 
Really appreciate you picking this up this a huge help for 1.0.

Left a couple comments.

Maybe once this is submitted @scottilee can help port it over to a py_func rather than using ksonnet.

**Comment by jinchihe** [comment]
@jlewi the checkout_repos.sh cannot recognize the PULL_BASE_SHA, usage is as below
```
Usage: checkout_repos --repos=<{REPO_ORG}/{REPO_NAME}@{SHA}:{PULL_NUMBER},{REPO_ORG}/{REPO_NAME}@HEAD:{PULL_NUMBER}> --src_dir=<Where to check them out> --links=<src1>=<dest1>,<src2>=<dest2>
```
Seems we can feed that as --repos options in 
```
--repos=kubeflow/examples@{SHA}:{PULL_NUMBER}
```

For presubmits, that can be 
```
--repos=kubeflow/examples@HEAD:$(PULL_NUMBER)
```
For non-presubmits, that can be
```
--repos=kubeflow/examples@{PULL_BASE_SHA}
```

**Comment by jinchihe** [comment]
@jlewi Updated to use use PULL_BASE_SHA for postsubmits as your above comments, thanks!

**Pull request merged**
