### PR TITLE
Fix issues with the xgboost_synthetic example and deploying the model.

### PR DESCRIPTION
**Pull request by jlewi**
* install newer version of fairing
* modify preprocessor to use custom dockerfile
* use newer 0.7 base image.
* Fix endpoint.

Related to:

kubeflow/examples#673 model doesn't deploy its crash looping
Related to kubeflow/examples#655 update example to work with 0.7

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/682)

### CODE REVIEW

**Comment by jlewi** [comment]
presubmit passed.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/682/kubeflow-examples-presubmit/1199076666912018440

The logs for get-credentials step indicate we are running against a new cluster

```
INFO|2019-11-25T21:27:26|/mnt/test-data-volume/kubeflow-examples-presubmit-notebooks-682-e80ff2b-8440-47ec/src/kubeflow/testing/py/kubeflow/testing/util.
py|72| kubeconfig entry generated for kf-vmaster-1125-876.
```

Here are the logs for notebooks test step in the graph

[kubeflow-examples-presubmit-notebooks-682-e80ff2b-8440-47ec-573328964.log.txt](https://github.com/kubeflow/examples/files/3888934/kubeflow-examples-presubmit-notebooks-682-e80ff2b-8440-47ec-573328964.log.txt)

Here is the output from paper mill
[xgboost-test-212744-f6a-jst7q.logs.txt](https://github.com/kubeflow/examples/files/3888959/xgboost-test-212744-f6a-jst7q.logs.txt)

So it looks like the notebook ran but lots of the cells don't produce output. Maybe there's a better way with papermill to capture the output? Does papermill produce a notebook? Should we capture that notebook and upload it as an artifact?

**Comment by jlewi** [comment]
This is ready for review.

/assign @kunmingg 
/assign @abhi-g

**Comment by abhi-g** [comment]
<p>/lgtm</p><p>Thanks for the fixes.</p>

**Comment by jlewi** [comment]
ok looks like adding /lgtm via notebook review app doesn't work; you need to comment directly on the PR.

**Pull request merged**
