### PR TITLE
Use the client libs to do a GCS copy instead of gsutil

### PR DESCRIPTION
**Pull request by amygdala**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/558)

### CODE REVIEW

**Comment by amygdala** [comment]
oops, I just realized that in the notebook, that 'datagen' step also needs to be converted to using the client libs to copy.  Will update.

**Comment by texasmichelle** [comment]
I get this error during the file copy:
```Traceback (most recent call last):
  File "/ml/train_model.py", line 147, in <module>
    main()
  File "/ml/train_model.py", line 110, in main
    copy_checkpoint(new_blob_prefix, target_bucket)
  File "/ml/train_model.py", line 54, in copy_checkpoint
    copy_blob(storage_client, source_bucket, blob, target_bucket, blob.name, new_blob_prefix, PREFIX)
  File "/ml/train_model.py", line 38, in copy_blob
    source_blob, target_bucket, new_blob_full_name)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/storage/bucket.py", line 1036, in copy_blob
data dir: gs://aju-dev-demos-codelabs/kubecon/t2t_data_gh_all/
model_startpoint: gs://aju-dev-demos-codelabs/kubecon/model_output_tbase.bak2019000
model_dir: gs://kubeflow-mcas-195423/codelab/github-issue-summarization-hm5vx/model_output
('target bucket: %s', 'kubeflow-mcas-195423')
('new_blob_prefix: %s', 'codelab/github-issue-summarization-hm5vx/model_output')
Copying files:
kubecon/model_output_tbase.bak2019000/checkpoint
Blob kubecon/model_output_tbase.bak2019000/checkpoint in bucket aju-dev-demos-codelabs copied to blob codelab/github-issue-summarization-hm5vx/model_output/checkpoint in bucket kubeflow-mcas-195423.
kubecon/model_output_tbase.bak2019000/eval/events.out.tfevents.1542926067.dl3
Blob kubecon/model_output_tbase.bak2019000/eval/events.out.tfevents.1542926067.dl3 in bucket aju-dev-demos-codelabs copied to blob codelab/github-issue-summarization-hm5vx/model_output/eval/events.out.tfevents.1542926067.dl3 in bucket kubeflow-mcas-195423.
kubecon/model_output_tbase.bak2019000/eval/events.out.tfevents.1543099877.dl3
Blob kubecon/model_output_tbase.bak2019000/eval/events.out.tfevents.1543099877.dl3 in bucket aju-dev-demos-codelabs copied to blob codelab/github-issue-summarization-hm5vx/model_output/eval/events.out.tfevents.1543099877.dl3 in bucket kubeflow-mcas-195423.
kubecon/model_output_tbase.bak2019000/events.out.tfevents.1542925846.dl3
    _target_object=new_blob,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 396, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.GoogleAPICallError: 413 POST https://www.googleapis.com/storage/v1/b/aju-dev-demos-codelabs/o/kubecon%2Fmodel_output_tbase.bak2019000%2Fevents.out.tfevents.1542925846.dl3/copyTo/b/kubeflow-mcas-195423/o/codelab%2Fgithub-issue-summarization-hm5vx%2Fmodel_output%2Fevents.out.tfevents.1542925846.dl3: Copy spanning locations and/or storage classes could not complete within 30 seconds. Please use the Rewrite method (https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) instead.```

**Comment by texasmichelle** [comment]
Looks like the file copy error was due to unknown bucket config errors.

/lgtm
/approve

**Pull request merged**
