### PR TITLE
remove obsolete PS in GPU jsonnet

### PR DESCRIPTION
**Pull request by Svendegroote91**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/407)

### CODE REVIEW

**Comment by jlewi** [comment]
Why is the PS no longer needed?

**Comment by Svendegroote91** [comment]
Hi Jeremy,

In the example I am running a single training job (TFjob) to train a model and I want to showcase the difference in training time when running it on a GPU instead of CPU. The standard PS component is obsolete for what I want to showcase and therefore I would like to remove it (to keep it as simple as possible).

Let me know in case I got this wrong.

Best regards,
Sven

Op 12 dec. 2018 om 19:01 heeft Jeremy Lewi <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Why is the PS no longer needed?

**Pull request merged**
