### PR TITLE
pin the web-ui version of TF to 1.7-- same as training

### PR DESCRIPTION
**Pull request by amygdala**
Newer versions give an import error.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/658)

### CODE REVIEW

**Comment by amygdala** [comment]
I don't believe the test failure is related to my (very small) change.

**Comment by jinchihe** [comment]
> Newer versions give an import error.

@amygdala could you please show the errors? I'm curious why have import error since tensorflow should be compatible :-)

**Comment by amygdala** [comment]
@jinchihe It's
`from tensorflow.examples.tutorials.mnist import input_data` causing the problem, which at some point must have been removed (or moved?).  The training `Dockerfile.model` uses `FROM tensorflow/tensorflow:1.7.0` and so they should probably stay synced anyway.

**Comment by jinchihe** [comment]
> @jinchihe It's
> `from tensorflow.examples.tutorials.mnist import input_data` causing the problem, which at some point must have been removed (or moved?). The training `Dockerfile.model` uses `FROM tensorflow/tensorflow:1.7.0` and so they should probably stay synced anyway.

Oh, understood, I remember `mnist` is moved to somewhere :-) Thank you!

**Comment by jinchihe** [comment]
ye, we need to take a look the ci tests.

**Comment by amygdala** [comment]
I wonder if we could just pull this in? 😬Don't know what is up w/ the tests, which I did not set up.

**Comment by jinchihe** [comment]
@amygdala Seems the test problem is not caused by the code change, seems caused by test env problem.

/retest

**Comment by jinchihe** [comment]
Get some logs, need deep investigation.
```
esting/util.py|42| Running: kustomize edit add configmap mnist-map-training --from-literal=secretMountPath=/var/secrets
cwd=/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/examples/mnist/training/GCS
INFO|2019-10-23T01:04:47|/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/testing/py/kubeflow/t
esting/util.py|57| Subprocess output:
error: SchemaError(io.k8s.api.certificates.v1beta1.CertificateSigningRequestList): invalid object doesn't have additional properties
ERROR|2019-10-23T01:04:49|/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/tf-operator/py/kubef
low/tf_operator/test_runner.py|72| There was a problem running the job; Exception Command 'kustomize build /mnt/test-data-volume/kubeflow
-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/examples/mnist/training/GCS| kubectl apply -f -' returned non-zero exit stat
us 1
Traceback (most recent call last):
 File "/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/tf-operator/py/kubeflow/tf_operator/tes
t_runner.py", line 53, in run_test
   test_func()
 File "tfjob_test.py", line 96, in test_train
   subprocess.check_call(subCmd, shell=True)
 File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
   raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'kustomize build /mnt/test-data-volume/kubeflow-examples-presubmit-mnist-658-e54ebb2-8672-22f7/src/kubeflow/e
xamples/mnist/training/GCS| kubectl apply -f -' returned non-zero exit status 1
```

**Comment by texasmichelle** [comment]
@amygdala Try rebasing since some issues with tests have been resolved in master.

**Comment by amygdala** [comment]
great, will do. (this had popped off my stack 😬)

**Comment by amygdala** [comment]
Hmm, still no luck apparently. (I haven't dug in to the test details yet).

**Comment by amygdala** [comment]
FINALLY the (unrelated) tests passed :)
@jinchihe or @texasmichelle , would you mind lgtm-ing/approving?

**Pull request merged**
