### PR TITLE
reduced number of layers

### PR DESCRIPTION
**Pull request by govindKAG**
combined the pip installs into one layer. Should slightly reduce the image size

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/481)

### CODE REVIEW

**Comment by texasmichelle** [comment]
It looks like the lint issues were resolved in #493. If you rebase, that should fix the failure.

**Comment by texasmichelle** [comment]
@govindKAG this should be ready to go after a rebase

**Comment by govindKAG** [comment]
sorry messed up a bit of git config there.

**Comment by texasmichelle** [comment]
Try a rebase & squash

**Comment by texasmichelle** [comment]
@govindKAG feel free to ask for help in kubeflow slack if you're running into trouble rebasing

**Comment by texasmichelle** [comment]
@govindKAG it would be great to get this merged. Can you rebase so that we can close this out?

**Comment by texasmichelle** [comment]
This PR is set to be closed at the end of the month due to no activity since Feb @govindKAG

**Pull request closed without merging**
