### PR TITLE
Add instructions to deploy the seldon core model

### PR DESCRIPTION
**Pull request by ankushagarwal**
Update the issue summarization end to end tutorial
to deploy the seldon core model to the k8s cluster

Update the sample request and response

Related to https://github.com/kubeflow/examples/issues/11

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/46)

### CODE REVIEW

**Comment by texasmichelle** [comment]
Looks good at first glance. Running through the additional steps to verify.

**Comment by ankushagarwal** [comment]
@texasmichelle Can you LGTM again?

**Pull request merged**
