### PR TITLE
add kube-nodered

### PR DESCRIPTION
**Pull request by NightLightTw**
### Goals
This is an end-to-end example. Kube-nodered is aiming to integrate Kubeflow/Kubebeters with node-red, leveraging node-red's low-code modules, and using Kubeflow resources (e.g. Kubeflow pipeline, Kserve) to enhance its AI/ML ability.

### Feature Area
It takes many laborious procedures to build a practical ML pipelines including pipeline docker file compilation and edit. Laborious manual operations on kubeflow package are required to observe trainning results.

### What is the use case or pain point?

Although kubeflow pipeline is a convenient tool for major ML operations such training and testting, it takes many laborious procedures to build a practical ML pipelines, not to mention switching between various ML algorithms and data sets. A graphical UI can provide a rapid deployment medium for ML developer, professional/non professional alike, to exercise an ML operation without starting from scratch. The following site provide some completed integration suites and examples for illustration of this op.

For other instructions, please refer to:
https://github.com/NightLightTw/kube-nodered

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I just wanted to link my response to the other issue with what I think your next steps should be:
- https://github.com/kubeflow/manifests/issues/2499#issuecomment-1699863245

**Review by kbthu — COMMENTED** [review]
I have read your readme file and code.  Basically, this repo. has great features such as low code development for IOT users to integrate Kubeflow's AI automation functionalities.  It should be welcomed by broad base of IOT and AI users alike.  However, I do find there are a few issues with the readme file.  They are as follows:
1.  The order of pre-requisites need to be stated clearly in an introduction section.  Don't put pre-requisites such as WSL, Docker, dependencies, etc. separately.  Instead, make a big bulletin called pre-requisites.  Move all the separate preparation works under it.
2. Move the beginning demo video containing the architecture illustration and the AI pipeline  operations of to the last part of readme file.
3. Make sure that all illustrations including GUI and explanation in English.  There are Chinese characters shown in the Node-red buttons in the configuration step.

**Comment by NightLightTw** [comment]
@kbthu 
Thank you, for your comment. I will revise the readme based on your guidance as soon as possible.

**Review by kbthu — APPROVED** [review]
The author has made significant improvement on the code structure and readme files.  This repo. has also included a vedio demonstrating the architecture.  The action of the Node-red visual pipeline over Kubeflow pipelines of three AI processes is also included at the end.   With these changes, it worths a go sign.

**Review by kbthu — COMMENTED** [review]
/lgtm

**Comment by NightLightTw** [comment]
@jinchihe we have received a lgtm from one of the reviewer for our repo.  Please help us to check the code quality and grant an approval.  Please feel free to give us suggestions.

**Review by justin0322 — APPROVED** [review]
/lgtm
/approve

**Pull request closed without merging**
