### PR TITLE
[pytorch_mnist] Automate image build

### LINKED ISSUE #312: [mnist_pytorch] Implement E2E tests
We should have E2E tests that cover:

1. Training the model
1. Deploying the model
1. Client code to send predictions
1. Notebook (if there is one)

### PR DESCRIPTION
**Pull request by dsdinter**
First step to fix #312 

TODO
Add E2E test to train model
Add E2E test to deploy model
Add E2E test to predict digits.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/490)

### CODE REVIEW

**Comment by jlewi** [comment]
Just an FYI; if you want me to review this remove WIP from the title. I assume if WIP is in the title its not ready for review.

**Comment by jlewi** [comment]
/assign @texasmichelle 
/assign @johnugeorge 

@johnugeorge Since you are one of the primary maintainers of PyTorch do you want to review this PR?

**Comment by johnugeorge** [comment]
With the upcoming release 0.5, v1alpha2 won't be supported. Supported versions would be v1beta1 and v1beta2

**Comment by dsdinter** [comment]
Hi @johnugeorge , thanks for the feedback. I bumped up versions to support v0.5.
I would appreciate your help to figure out the best way to test train and deploy jobs for the pytorch model.
I believe the idea at the moment is to use the test_runner module from tf-operator but wondering if we can use something like pytest to reduce dependencies between components.


Thanks.

**Comment by jlewi** [comment]
Yes. You can use the pytest module. I believe mnist TF is using tat now at least for deploy.
https://github.com/kubeflow/examples/blob/master/mnist/testing/predict_test.py

@johnugeorge @dsdinter what's the best way to push through this PR. It looks like this PR is doing three things

1. Setup CI for the docker images.
1. Adding E2E test for training
1. Adding E2E test for prediction.

Would breaking this up into 3 smaller PRs help make progress?

**Comment by johnugeorge** [comment]
I have the same opinion.  @dsdinter what do you think?

**Comment by dsdinter** [comment]
I agree, part 1. is complete I believe.
Happy to change the test modules as dummy ones to pass always, then close this PR, let me change the title.

**Comment by jlewi** [comment]
I'll let @johnugeorge handle reviewing this PR; if you need me for something let me know.

**Comment by dsdinter** [comment]
Thanks @jlewi , @johnugeorge please review and let me know if you are happy to approve.

Kind regards.

**Comment by johnugeorge** [comment]
Looks good to me. Anything pending in this?

**Comment by dsdinter** [comment]
@texasmichelle @jlewi feel free to approve this PR.

Thanks.

**Comment by texasmichelle** [comment]
Thanks to you both for working on this!

/approve

**Pull request merged**
