### PR TITLE
Remove reviewers who are already approvers

### PR DESCRIPTION
**Pull request by texasmichelle**
Remove @ScorpioCPH and @zjj2wry due to inactivity (no PRs or comments on PRs).

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/247)

### CODE REVIEW

**Comment by zjj2wry** [comment]
@texasmichelle not lgtm，will be invested in kubeflow soon，thanks

**Comment by texasmichelle** [comment]
Great, thanks for the update @zjj2wry. Added you back to OWNERS as a reviewer

**Comment by texasmichelle** [comment]
@cwbeitel Got time to review this?

**Comment by cwbeitel** [comment]
Yeah /lgtm I'm presuming when you went through and made those changes you knew what you were doing, haven't seen a response from the other person you removed, and as for myself happy to review examples here and there.

**Comment by cwbeitel** [comment]
I guess it wanted that on a separate line
/lgtm

**Pull request merged**
