### PR TITLE
Reinforcement learning example with TensorFlow Agents

### PR DESCRIPTION
**Pull request by cwbeitel**
See also https://github.com/kubeflow/examples/pull/1, https://github.com/cwbeitel/examples-old for previous PR

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/30)

### CODE REVIEW

**Comment by cwbeitel** [comment]
Assigning original reviewers:
/assign jlewi
/assign nkashy1
/assign danijar

**Comment by cwbeitel** [comment]
@nkashy1 Awesome I can definitely add that to a subsequent version, thanks for the feedback.

**Comment by jlewi** [comment]
Reviewed 11 of 27 files at r1.
Review status: 11 of 27 files reviewed at latest revision, all discussions resolved.

---

*[agents/README.md, line 3 at r1](https://beta.reviewable.io/reviews/kubeflow/examples/30#-L6z2Mprx0lbn-jTOf1K:-L6z2Mprx0lbn-jTOf1L:bmke9dh) ([raw file](https://github.com/kubeflow/examples/blob/4e1e42a0884cb5720dd55e1ed89aa3b343ece9ea/agents/README.md#L3)):*
> ```Markdown
> # Reinforcement Learning with [tensorflow/agents](https://github.com/tensorflow/agents)
> 
> [Docker Repository on Quay](https://quay.io/repository/cwbeitel/agents-demo)
> ```

Lets not reference a personal container image. Please delete this and file an issue to publish a container if need be. If you want you can put a link to your Docker image in the container.

For the instructions you could just tell users to build the container and push it to the registry of their choice.

---

*[agents/README.md, line 50 at r1](https://beta.reviewable.io/reviews/kubeflow/examples/30#-L6z32c5MPraXIHRsURO:-L6z32c5MPraXIHRsURP:b8jauxr) ([raw file](https://github.com/kubeflow/examples/blob/4e1e42a0884cb5720dd55e1ed89aa3b343ece9ea/agents/README.md#L50)):*
> ```Markdown
> We might want to include various additional dependencies in our notebook container to aid in development of our model. In that case we might be interested in modifying the demo Dockerfile and re-building the container.
> 
> The demo container can be built using the standard workflow:
> ```

Just move these instructions to the top

---

*[agents/doc/Dockerfile, line 13 at r1](https://beta.reviewable.io/reviews/kubeflow/examples/30#-L6z3w3EBWdbcxFsRCEW:-L6z3w3EBWdbcxFsRCEX:bdpmt70) ([raw file](https://github.com/kubeflow/examples/blob/4e1e42a0884cb5720dd55e1ed89aa3b343ece9ea/agents/doc/Dockerfile#L13)):*
> ```Dockerfile
> # limitations under the License.
> 
> FROM gcr.io/kubeflow/tensorflow-notebook-cpu
> ```

What's this container for?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kubeflow/examples/30)*

**Comment by cwbeitel** [comment]
Review status: 10 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[agents/doc/Dockerfile, line 13 at r1](https://beta.reviewable.io/reviews/kubeflow/examples/30#-L6z3w3EBWdbcxFsRCEW:-L72rAVM1bOyMgDRZhDi:b-8j2jio) ([raw file](https://github.com/kubeflow/examples/blob/4e1e42a0884cb5720dd55e1ed89aa3b343ece9ea/agents/doc/Dockerfile#L13)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

What's this container for?
</blockquote></details>

Not necessary (now/given) that gcloud and ks are available through the base container and renders aren't working in-notebook so the ffmpeg dependency doesn't justify the burden of working with a secondary container. See also commit notes.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kubeflow/examples/30)*

**Comment by jlewi** [comment]
Woo Hoo! Great Work
/lgtm
/approve

**Comment by danijar** [comment]
Congrats to getting this first step into the code base!

**Comment by danijar** [comment]
(Not sure why Github shows me "danijar unassigned nkashy1" but it seems like I can't change it back.)

**Pull request merged**
