### PR TITLE
[pytorch_mnist] Point images back to gcr.io/kubeflow-examples

### PR DESCRIPTION
**Pull request by dsdinter**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/360)

### CODE REVIEW

**Comment by dsdinter** [comment]
/assign @jlewi 
Thanks!

**Comment by jlewi** [comment]
Examples should use the registry
gcr.io/kubeflow-examples
Not 
gcr.io/kubeflow-images-public

**Comment by dsdinter** [comment]
Doh! You are right, I believe I got confused with a comment in the original PR to use the kubeflow-images-public for postsubmits.

**Pull request merged**
