### PR TITLE
[Financial Time Series] Update example to v0.4.0 and add Kubeflow pipelines

### PR DESCRIPTION
**Pull request by Svendegroote91**
- update to Kubeflow v0.4.0 and simplified set-up script
- slightly refactor code for kubeflow pipelines
- add kubeflow pipelines

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/535)

### CODE REVIEW

**Comment by Svendegroote91** [comment]
I rebased so my PR is again in sync with latest master.
@cwbeitel  and @gaocegege : when would you be able to have a look at this PR?

**Comment by Svendegroote91** [comment]
Hi, I again synced my branch so it's up to date with current master branch here.
@texasmichelle any chance when this can be reviewed?

**Comment by Svendegroote91** [comment]
Any update on when this can be reviewed @cwbeitel or @gaocegege ?

**Comment by Svendegroote91** [comment]
hi @texasmichelle , any idea when this PR could be reviewed? I want to release a blog post on kubeflow pipelines (which was added as part of this PR) but it's depending on this PR.

**Comment by abhi-g** [comment]
@texasmichelle would you have time to review this PR? The change looks reasonable to me, but I am neither an owner or a reviewer on this repo.

**Comment by Svendegroote91** [comment]
Hi @gabrielwen , I resynced again with master so it's again in sync. Any possibility to get a review on this?

**Comment by texasmichelle** [comment]
So sorry for the late review - thank you for the updates!

/lgtm
/approve

**Pull request merged**
