### PR TITLE
Move example to third_party folder

### PR DESCRIPTION
**Pull request by texasmichelle**
Move GitHub issue summarization example into a third_party folder since
it is not Apache 2 licensed.
Add LICENSE file from original repo:
  (https://github.com/hamelsmu/Seq2Seq_Tutorial)
Remove redundancy in folder name

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/19)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
LGTM

**Comment by jlewi** [comment]
Can't we just change the license?

**Comment by texasmichelle** [comment]
@hamelsmu can you do that in your original repo so that I can close this PR?

**Comment by ankushagarwal** [comment]
@texasmichelle : The original repo already has the [LICENSE](https://github.com/hamelsmu/Seq2Seq_Tutorial/blob/master/LICENSE)

**Comment by jlewi** [comment]
@texasmichelle @ankushagarwal 
@hamelsmu  already contributed the code to the kubeflow repo and when he did so he signed our CLA. So at this point I think we can modify the code as needed which includes changing the license. 

In other words, the question is now what license would Kubeflow like to attach to its example and I think we should just use Apache and not MIT.

**Comment by hamelsmu** [comment]
Hey folks I'm happy to change the license, its not a big deal for me, however the root of this repo already has Apache License?  I'll change my license now (I'm impartial Apache vs. MIT)

**Comment by hamelsmu** [comment]
Update the license [in the original repo](https://github.com/hamelsmu/Seq2Seq_Tutorial) is now Apache 2.0.

**Comment by texasmichelle** [comment]
Great, thanks all!! 

I moved the folder back to top-level & left the rename intact to remove redundancy. MIT license file is now gone.

**Comment by ankushagarwal** [comment]
@texasmichelle  Can you resolve the conflicts?

**Comment by texasmichelle** [comment]
Ignoring unrelated presubmit tests since they will be resolved by [PR-18](https://github.com/kubeflow/examples/pull/18).

**Pull request merged**
