### PR TITLE
Write xgboost_synthetic test output to html

### PR DESCRIPTION
**Pull request by gabrielwen**
Write testing notebook to GCS:

https://pantheon.corp.google.com/storage/browser/kubeflow-ci-deployment/xgboost_synthetic_testing?project=kubeflow-ci-deployment

Related: kubeflow/manifests#757

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/735)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen this is great. Instead of writing it to a bucket in kubeflow-ci-deployment; could we write it to the GCS location used by prow for results so that it shows up in spyglass?

1. Here's the [spyglass results](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/735/kubeflow-examples-presubmit/1228118624045109248/) for the most recent presubmit run 
1. I'd like to click on [artifacts](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/735/kubeflow-examples-presubmit/1228118624045109248/) and see the HTML file there.

You can use this function to get the gcs_dir for the results based on the environment variables that prow sets.
https://github.com/kubeflow/testing/blob/43b78260019e15be19a29800a88fa63a6e132bae/py/kubeflow/testing/prow_artifacts.py#L110

**Comment by gabrielwen** [comment]
> @gabrielwen this is great. Instead of writing it to a bucket in kubeflow-ci-deployment; could we write it to the GCS location used by prow for results so that it shows up in spyglass?
> 
> 1. Here's the [spyglass results](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/735/kubeflow-examples-presubmit/1228118624045109248/) for the most recent presubmit run
> 2. I'd like to click on [artifacts](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/735/kubeflow-examples-presubmit/1228118624045109248/) and see the HTML file there.
> 
> You can use this function to get the gcs_dir for the results based on the environment variables that prow sets.
> https://github.com/kubeflow/testing/blob/43b78260019e15be19a29800a88fa63a6e132bae/py/kubeflow/testing/prow_artifacts.py#L110

seems like the pod running `execute_notebook` doesn't have permission to write to that GCS bucket.  let me see how to make this work.

**Comment by jlewi** [comment]
@gabrielwen the pod that's running the pytest (i.e. that launches the K8s job) should have permission to write to kubernetes-jenkins. So that pod could copy it from the GCS location that execute_notebook writes to.

**Comment by gabrielwen** [comment]
> @gabrielwen the pod that's running the pytest (i.e. that launches the K8s job) should have permission to write to kubernetes-jenkins. So that pod could copy it from the GCS location that execute_notebook writes to.

right, that's exactly I'm trying to do.

**Comment by jlewi** [comment]
@gabrielwen let me know when this is ready for another review?

**Comment by gabrielwen** [comment]
@jlewi 

ok, it's just ready for another look:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/735/kubeflow-examples-presubmit/1228467199899865088/artifacts/junit_kubeflow-examples-presubmit-notebooks-735-09045fb-5088-7a30/xgboost-synthetic-test-notebooks/notebook.html

**Pull request merged**
