### PR TITLE
update to kubeflow-metadata in examples

### PR DESCRIPTION
**Pull request by jinchihe**
Fixes: #645 

Updated examples to kubeflow.metadata since the metadata SDK has been renamed to kubeflow-metadata in the PR kubeflow/metadata#131.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/646)

### CODE REVIEW

**Comment by jinchihe** [comment]
The pylint check failed 
```
E: 20, 0: No name 'metadata' in module 'kubeflow' (no-name-in-module)
```
That's caused by that there is a `kubeflow` under `PYTHONPATH` in the test steps, so cannot found the `metadata` under the `PYTHONPATH/kubeflow`
```
     name: PYTHONPATH
      value: '/mnt/test-data-volume/kubeflow-examples-presubmit-unittests-646-2d907a1-6512-f4ce/src/kubeflow/examples:/mnt/test-data-volume/kubeflow-examples-presubmit-unittests-646-2d907a1-6512-f4ce/src/kubeflow/testing/py'
```

I think we can just ignore that,

**Comment by jinchihe** [comment]
/assign @zhenghuiwang 

Could you please help to review? Thanks a lot!

**Comment by zhenghuiwang** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
