### PR TITLE
Mnist pipelines

### PR DESCRIPTION
**Pull request by DanSanche**
Added example for Kubeflow Pipelines using the MNIST sample

cc: @sarahmaddox

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/524)

### CODE REVIEW

**Comment by DanSanche** [comment]
/assign @texasmichelle 

Sarah told me you might want to review this?

**Comment by texasmichelle** [comment]
Looks great!! Thanks @DanSanche 

/approve
/lgtm

**Pull request merged**
