### PR TITLE
fix miscellaneous bugs for azurepipeline example

### PR DESCRIPTION
**Pull request by umialpha**
fix a few bugs for azure pipeline example, #670 ,

fix syntax error in

> train.py 

>  register.py

according to the azure ML example(https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/machine-learning/service/how-to-deploy-and-where.md), fix bugs in

> profile/score.py 

> deploy/score.py

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/695)

### CODE REVIEW

**Comment by squillace** [comment]
@umialpha does this need rebasing? Really looking forward to this.

**Comment by squillace** [comment]
tagging also @azooinmyluggage

**Comment by jlewi** [comment]
Looks like lint is failing can you fix that please?

**Comment by jlewi** [comment]
kubeflow/examples#728 should disable the tests once that's merged you should be able to rebase and the tests will pass.

**Comment by umialpha** [comment]
> @umialpha does this need rebasing? Really looking forward to this.

sry for the delay. I completely forget this pr. I will check it again.

**Comment by squillace** [comment]
And @umialpha I want to thank you for your work here. I'm very grateful.

**Comment by jlewi** [comment]
#728 is merged
So if you rebase of the latest master that should fix the tests.
/assign jlewi

**Comment by berndverst** [comment]
@umialpha let's get your PR through to the finish. Can you pull the latest master and then rebase your branch and force push? Tests should succeed then. After that we should be able to get this merged.

**Comment by umialpha** [comment]
> @umialpha let's get your PR through to the finish. Can you pull the latest master and then rebase your branch and force push? Tests should succeed then. After that we should be able to get this merged.

I will try to rebase and push again in this week. Sry for the delay.

**Pull request closed without merging**
