### PR TITLE
Remove multiple import statements in Mnist example

### PR DESCRIPTION
**Pull request by kurianbenoy**
In Kubeflow examples notebook, I found multiple import statements in kubeflow Mnist GCP deployment

### CODE REVIEW

**Comment by kurianbenoy** [comment]
@googlebot I signed it

**Comment by NikeNano** [comment]
The jobs(xgboost-synthetic, mnist) seems to timeout for : 
```Job has reached the specified backoff limit, reason: BackoffLimitExceeded,
   status: 'True', type: Failed``` :(

**Comment by jlewi** [comment]
I think the tests will continue to fail until #795 is commited.

**Pull request closed without merging**
