### PR TITLE
minor update to the pachyderm seldon example

### PR DESCRIPTION
**Pull request by Nick-Harvey**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/562)

### CODE REVIEW

**Comment by texasmichelle** [comment]
It looks like the tf-job test is failing after [this step](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/testing/tfjob_test.py#L73):
INFO|2019-06-17T21:29:45|tfjob_test.py|73| Waiting for job to finish.
ERROR|2019-06-17T21:29:45|/mnt/test-data-volume/kubeflow-examples-presubmit-gis-562-ef668db-7492-87c4/src/kubeflow/tf-operator/py/kubeflow/tf_operator/tf_job_client.py|155| There was a problem waiting for Job gis-test-1140731598069567492.gis-test-1140731598069567492; Exception; (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 17 Jun 2019 21:29:45 GMT', 'Audit-Id': 'e6098e93-a88f-48d9-bef9-f19a65b2ef61', 'Content-Length': '19', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: 404 page not found

Full logs [here](https://drive.google.com/a/kubeflow.org/file/d/1Z3AcoB8oNer4i_mqglcZRTrHikWFsjFD/view?usp=sharing).

@jlewi any idea why this test is failing? Seems to be unrelated to this PR

**Comment by jinchihe** [comment]
Seems the code change is not related with the test error. @Nick-Harvey could you please just fix rebase, and push to trigger one more presubmit testing? Thanks.

**Comment by jlewi** [comment]
Test failures look unrelated to this PR.
This PR is just modifying the README and the pachyderm file. So I'll just go ahead and merge manually.

**Pull request merged**
