### PR TITLE
[WIP] Pix2Pix TF2.0 Pipelines Notebook - Request for intial feedback

### PR DESCRIPTION
**Pull request by fdasilva59**
**Work in progress for [#876](https://github.com/kubeflow/website/issues/876)**

**Goal of this PR is for me to get a first review/feedback**  on the work in progress (both on code and UX/scenario),  so I can  see what to correct/improve (FYI, this is my first "community sprint" :) )

Available so far:
- Pipelines with 2 components : download_dataset and prepare_dataset - Release Candidates
- The main Notebook using these 2 components - Work in Progress

Remaining Work:
- Create train and test pipelines components + add them in the notebook pipelines
- write the setup instructions (Maybe [reuse this one](https://github.com/fdasilva59/Pix2Pix-Kubeflow-Demo/blob/master/SETUP.md), but without IAP setup and with added "gcloud services enable cloudbuild.googleapis.com" ? 
- write a readme
- test end-to-end

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/596)

### CODE REVIEW

**Comment by fdasilva59** [comment]
@googlebot I fixed it.

**Comment by sarahmaddox** [comment]
Hallo @fdasilva59 thanks for the further updates! Is this PR ready for technical review? If so, I suggest @amygdala as reviewer.

**Comment by jlewi** [comment]
When the PR is ready for review please remove WIP from the title.

**Comment by fdasilva59** [comment]
Hi @sarahmaddox @jlewi  !

The PR is not yest fully ready:

- [WIP] README + SETUP are still WIP (though well advanced, no commit yet)
- [CLA ISSUE] It looks like I have now a CLA issue (it was ok before): I might have better not synced my fork with the upstream... : it now looks like in the presubmit process logs, that files I don't own are being checked (??) That might explain why the CLA check now fails. But the file list associated with this PR is good. Not sure what to do here. Maybe delete the PR, make a clean fork of the repo, add my files and recreate a clean PR ? Any suggestion ?

- [TF2.0 ISSUE] Otherwise I have a some questions/troubles with Tensorflow 2.0 regarding saving and restoring models (that the last modification I'd like to include in my code): 
 
1.  See https://stackoverflow.com/questions/57758466/is-it-possible-to-restore-tensorflow-2-0-checkpoints-for-inference-with-a-gener  (**Not blocking**: Autograd and checkpoints restore strange behavior)
2. I would like to include a pretrained model in github (to avoid 2 hours of training) The checkpoints are too heavy to be added in github. So I try to save & restore my pix2pix generator  model with TF2.0 (following the example in https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators)... but if the inference step returns a Tensor of good size...it is filled only with NaNs. Maybe I should open a github Tensorflow issue with that one ?? (The Tensorflow collab tutorial works fine. But this does not seem to work with my pix2pix generator model)

```
# Generator model was saved like this : 
#tf.saved_model.save(generator, pathmodel + "pix2pix/1/")

!saved_model_cli show --dir /mnt/nfs/data/test_model/pix2pix/1/ --tag_set serve --signature_def serving_default

import tensorflow as tf
loaded = tf.saved_model.load("/mnt/nfs/data/test_model/pix2pix/1/")
print(list(loaded.signatures.keys()))  # ["serving_default"]

infer = loaded.signatures["serving_default"]
print(infer.structured_outputs)

np.random.seed(0)
dummy = np.random.uniform(-127.5, 127.5, (1, 256, 256, 3)).astype(np.float32)
dummy = tf.convert_to_tensor(dummy, dtype=tf.float32)
print(dummy[0][0:5][0][0])
print("\n\nInference:\n")

out = infer(dummy)['conv2d_transpose_7']
print(out[0][0:5][0][0])
```

which returns

```
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 3)
      name: serving_default_input_1:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['conv2d_transpose_7'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 3)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
['serving_default']


{'conv2d_transpose_7': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='conv2d_transpose_7')}

tf.Tensor([12.447444 54.873287 26.20466 ], shape=(3,), dtype=float32)

Inference:
tf.Tensor([nan nan nan], shape=(3,), dtype=float32)
```

**Comment by sarahmaddox** [comment]
Hallo @fdasilva59 The CLA issue seems to be because one or more of your commits is using a different email address from the one with which you signed the CLA. The email address that doesn't yet have a CLA is your own email address at worldline.com.

For the TensorFlow questions, it's best to ask @amygdala for pointers.

**Comment by fdasilva59** [comment]
Thanks @sarahmaddox . I spoted the faulty commit. I'll try to fix that particular commit to fix the CLA  check error.

Regarding the Tensorflow 2.0 difficulty: I am trying to get help on stackoverflow. I also tried to ping Page Bailey and Martin Görner on Twitter. Let's wait for some feedback.

- https://twitter.com/fdasilva59fr/status/1174715624054038531
- https://stackoverflow.com/users/10956395/fabien?tab=questions

**Comment by jlewi** [comment]
@fdasilva59 what are the next steps with this PR?

**Comment by texasmichelle** [comment]
@fdasilva59 please identify your outstanding questions here so that we can get the right folks involved.

**Pull request closed without merging**
