### PR TITLE
Update demo script & add notebook

### PR DESCRIPTION
**Pull request by texasmichelle**
Update demo script to include deploy script and notebook created by @drscott173
Simplify by removing unnecessary commands
Use default namespace instead of kubeflow

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/248)

### CODE REVIEW

**Comment by texasmichelle** [comment]
@lluunn Could you also approve plz?

**Comment by lluunn** [comment]
/lgtm
/approve
I thought I can't approve in this repo, but I will try anyway.

**Pull request merged**
