### PR TITLE
Create a notebook for mnist E2E on AWS

### PR DESCRIPTION
**Pull request by Jeffwan**
A notebook to run the mnist E2E example on AWS. This is based on GCP's work in this PR https://github.com/kubeflow/examples/pull/723. 

This PR is to address https://github.com/kubeflow/examples/issues/724

Resolve a few issues.

1. Ingress endpoint is a little bit different and we create a new method `get_ingress_endpoint ` in utils to expose the hostname

2. Make GCP setup in notebook_setup optional by passing a platform argument. There's no specific config for AWS at this moment, just skip GCP setting

3. Use AWS ECR in fairing to build mnist image using cloud builder. It's a little bit trick and we have to `add_aws_credentials_if_exists` and `add_ecr_config` to let kaniko leverage ECR credential helper. 

4. Add environment directly in training, monitoring, serving. Get ride of most of the unnecessary parameters and only attach `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_REGION`

5. IAM for service account is not fully merged yet, once it's supported, I will update the examples to skip credential settings.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/739)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@jlewi close old one for some reason and please review this one. Already address your comments in this PR.

**Comment by jlewi** [comment]
/lgtm
/approve

You will need to resolve the conflicts.

**Comment by Jeffwan** [comment]
@jlewi rebase the master changes and resolve the conflicts.

**Pull request merged**
