### PR TITLE
Remove redundant PULL

### PR DESCRIPTION
**Pull request by hholst80**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/648)

### CODE REVIEW

**Comment by texasmichelle** [comment]
It looks like there is a faulty test in the presubmits. If #653 is merged first, you should be able to rebase & clear this out. You might also try adding the code from that fix here.

**Comment by hholst80** [comment]
Sorry, I didn't pay attention to the details of the PR, it not being merged yet. I'll await the merge of that PR before retrying the build.

**Comment by texasmichelle** [comment]
Unfortunately, what seemed like a straightforward fix is triggering other issues. The test infra needs to be overhauled anyway, but that will be a much larger effort. I'll report back here when I make progress either way.

**Comment by texasmichelle** [comment]
@hholst80 Try rebasing since the presubmit failures have been resolved in master.

**Comment by texasmichelle** [comment]
ping @hholst80 I'd love to see this merged - please try rebasing to see if tests pass.

**Comment by texasmichelle** [comment]
Closing due to inactivity.

**Pull request closed without merging**
