### PR TITLE
[Not for review] Experiment triggering automated test workflow

### PR DESCRIPTION
**Pull request by cwbeitel**
@jlewi can you /ok-to-test this so I can debug the setup for the test workflow to trigger via GitHub?

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/25)

### CODE REVIEW

**Comment by jlewi** [comment]
/ok-to-test
Sent you an invite to the org so you can trigger the tests.

Note @texasmichelle is working on the tests. See #18

**Comment by cwbeitel** [comment]
Oh sorry @texasmichelle I thought we needed to have a separate test workflow for each example, I'll just stick to local tests then.

**Comment by texasmichelle** [comment]
We do want separate tests for each workflow, but the other PR needs to be merged first. I'm just waiting for the go-ahead from @jlewi, then you should be able to rebase & add your tests.

**Pull request closed without merging**
