### PR TITLE
Enhance mnist trainer to read args from command line

### PR DESCRIPTION
**Pull request by jinchihe**
fixes: #491

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/492)

### CODE REVIEW

**Comment by jinchihe** [comment]
/assign @jlewi 

That's wield... the failing phenomenon of kubeflow-examples-presubmit is changed, but did not get the real reason, it's grateful if you could take a look. Thanks a lot!

**Comment by jlewi** [comment]
If you look at the failing workflow there was a problem getting the kubeconfig for the cluster where the examples are supposed to run

```
W
+ gcloud auth activate-service-account --key-file=/secret/gcp-credentials/key.json
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
+ gcloud --project=kubeflow-ci container clusters get-credentials --zone=us-east1-d kf-v0-4-n00
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/kubeflow-ci/zones/us-east1-d/clusters/kf-v0-4-n00.
No cluster named 'kf-v0-4-n00' in kubeflow-ci.
```

**Comment by jlewi** [comment]
/test all

It failed because @gabrielwen is working on getting the clusters where examples run auto-updated: see kubeflow/testing#95 

Right now the clusters periodically disappear and tests will fail. @gabrielwen is working on fixing that but for now the solution is to just retry.

**Comment by jlewi** [comment]
@jinchihe if the predict test is still failing can we mark it as an expected failure using pytest so it doesn't block presubmit?

**Comment by jinchihe** [comment]
> @jinchihe if the predict test is still failing can we mark it as an expected failure using pytest so it doesn't block presubmit?

@jlewi Sorry for late reply due to Chinese New Year :-)  Yes, I think we can. but I will try one more time, thanks.

**Comment by jinchihe** [comment]
Seems all tests passed but lint check failed as beflow, and lint error files are not related with the PR change. 

```
ERROR|2019-02-11T03:00:56|test_py_lint.py:75| 4 files had lint errors:
/github_issue_summarization/testing/tfjob_test.py
/mnist/testing/deploy_test.py
/mnist/testing/tfjob_test.py
/mnist/web-ui/mnist_client_test.py
```

**Comment by jlewi** [comment]
@jinchihe Is the lint test broken at head? Maybe you need to rebase to pull in the latest changes?

**Comment by jinchihe** [comment]
> @jinchihe Is the lint test broken at head? Maybe you need to rebase to pull in the latest changes?

I think the lint test may has been broken before, although I didn't see where it was caused, but I think that's not caused by the PR changes. Thanks.

**Comment by jlewi** [comment]
See kubeflow/examples#505 
Lets get the lint test fixed first.

**Comment by jlewi** [comment]
I think the lint test might be fixed at HEAD; you might just need to rebase.

**Comment by jlewi** [comment]
Looks like the mnist E2E test is failing on both training and prediction. Not sure if its related to this PR or not.

**Comment by sarahmaddox** [comment]
Hallo @jlewi @jinchihe @DanSanche Do you know when the breaking builds will be fixed? I'm waiting on the merge of this PR in order to create a Pipelines end-to-end tutorial (issue https://github.com/kubeflow/website/issues/340).

**Comment by jinchihe** [comment]
I do not think the the test failure is related with the PR code changes.

Retested, that's strange, one workflow failed due to compnent py-lint component cannot save log.

```
INFO|2019-02-21T08:51:49|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|24| Workflow kubeflow-examples-presubmit-examples-e2e-492-485bfae-1371-4882 in namespace kubeflow-test-infra; **phase=Failed**
```
Chcked detailed argo logs below (compnent py-lint component cannot save log).
```
INFO|2019-02-21T08:48:17|test_py_lint.py:77| No lint issues.
INFO|2019-02-21T08:48:17|test_helper.py:62| Writing file: /mnt/test-data-volume/kubeflow-examples-presubmit-examples-e2e-492-485bfae-1371
-4882/output/artifacts/junit_py-lint.xml
**failed to create fsnotify watcher: too many open files**

Message: failed to save outputs: verify serviceaccount kubeflow-test-infra:default has necessary privileges
```

**Comment by jinchihe** [comment]
@jlewi Unlucky, the [test](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/492/kubeflow-examples-presubmit/1374/) is failed in mnist-test which was successful in yesterday tests, I think that's not related with code changes, and seems that's same with PR #499 testing. The tests are not stable, always failed in different places for some strange reasons.

**Comment by jlewi** [comment]
@jinchihe Should we hold off merging this code until the training job test is fixed?

#499 was changing tensorboard code and so was unrelated to the failing test.

This code is changing the trainer code which is the code that is being tested.

The logs for the training job show

```
INFO|2019-02-22T07:14:44|tfjob_test.py|79| Final TFJob:
{
 "status": {
   "completionTime": "2019-02-22T07:14:26Z",
   "conditions": [
     {
       "status": "True",
       "lastUpdateTime": "2019-02-22T07:13:42Z",
       "lastTransitionTime": "2019-02-22T07:13:42Z",
       "reason": "TFJobCreated",
       "message": "TFJob mnist-test-1375 is created.",
       "type": "Created"
     },
     {
       "status": "False",
       "lastUpdateTime": "2019-02-22T07:14:21Z",
       "lastTransitionTime": "2019-02-22T07:14:21Z",
       "reason": "TFJobRunning",
       "message": "TFJob mnist-test-1375 is running.",
       "type": "Running"
     },
     {
       "status": "True",
       "lastUpdateTime": "2019-02-22T07:14:26Z",
       "lastTransitionTime": "2019-02-22T07:14:26Z",
       "reason": "TFJobFailed",
       "message": "TFJob mnist-test-1375 has failed because 1 Chief replica(s) failed.",
       "type": "Failed"
     }
   ],
   "replicaStatuses": {
```

So it looks like the chief is failing.

It also looks like it is failing on master in the periodic test runs.
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-examples-mnist-90-70fd?tab=workflow&nodeId=kubeflow-periodic-examples-mnist-90-70fd-1605631456&sidePanel=logs%3Akubeflow-periodic-examples-mnist-90-70fd-1605631456%3Amain

**Comment by jlewi** [comment]
I filed #515 to fix the training test.

**Comment by jlewi** [comment]
/test all

@gabrielwen changed the cron job so it should run less frequently so the cluster should stay up long enough to manually tweak things.

I think we might just need to use 
https://github.com/jlewi/kubeflow-dev/blob/master/hack/fix_gcp_sa_permissions.py

To delete and recreate the role bindings for the service account to fix the issue (at least until the deployment is recreated).

That should hopefully be sufficient to give us a passing run and get this merged.

**Comment by jinchihe** [comment]
@jlewi Great thanks! Seem the `kubeflow-example-presubmit` has been passed after the cron job changed. Please let me know if any more reviewing comments for the PR changes. Thanks!

**Pull request merged**
