### PR TITLE
Update test cluster name

### LINKED ISSUE #652: Update cluster name in xgboost test
Presubmit tests are failing because they reference a cluster that no longer exists:
```+ gcloud --project=kubeflow-ci container clusters get-credentials --zone=us-east1-d kf-v0-4-n00
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/kubeflow-ci/zones/us-east1-d/clusters/kf-v0-4-n00.
No cluster named 'kf-v0-4-n00' in kubeflow-ci.
```

Update the cluster name and zone [here](https://github.com/kubeflow/examples/blob/master/test/workflows/components/xgboost_ames_housing.jsonnet#L22-L23).

### PR DESCRIPTION
**Pull request by texasmichelle**
Fixes #652

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/653)

### CODE REVIEW

**Comment by texasmichelle** [comment]
@puneith or @jlewi Any idea why this change is causing this error?
`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by jlewi** [comment]
No idea why this is triggering that bug.
I think we've seen other issues with ksonnet.
e.g.
https://github.com/kubeflow/testing/issues/459

/lgtm
/approve

**Comment by jlewi** [comment]
One way to fix this issue is to use this as motivation to migrate the E2E workflow of ksonnet.
You would just need to define a python function that creates the Argo workflow.

See here:
https://github.com/kubeflow/testing#python-function

Example workflow:
https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py

**Comment by texasmichelle** [comment]
Created #657 for the longer-term fix suggested above

**Comment by texasmichelle** [comment]
Closing as unnecessary now that test infra no longer uses ksonnet.

**Pull request closed without merging**
