### PR TITLE
Update Azure End to End Example in line with recent docs change

### PR DESCRIPTION
**Pull request by omartin2010**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/768)

### CODE REVIEW

**Comment by omartin2010** [comment]
adding @berndverst

**Comment by berndverst** [comment]
@omartin2010 change subject to "Update Azure End to End Example in line with recent docs change" or something like that

**Comment by omartin2010** [comment]
Hi team, anything we can do to help get the changes in? The documentation changes are accepted and people following the documentation wouldn't be able to if it's not synched with the code example. Thanks!

**Pull request merged**
