### PR TITLE
Modify readme to match the actual source code

### PR DESCRIPTION
**Pull request by janeman98**
Currently, the "Pipeline Breakdown" section of readme does not match the actual source code in https://github.com/kubeflow/examples/blob/master/pipelines/mnist-pipelines/mnist_pipeline.py. 

Use this PR to sync the readme with the actual source code.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/659)

### CODE REVIEW

**Comment by jinchihe** [comment]
@janeman98 Looks great! Thanks.

/lgtm
/approve

**Comment by janeman98** [comment]
Many thanks, @jinchihe!

**Pull request merged**
