### PR TITLE
fix import issue in the mnist e2e testing

### PR DESCRIPTION
**Pull request by jinchihe**
fixes: #530

* Move to the test clusters in project kubeflow-ci-deployment

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/531)

### CODE REVIEW

**Comment by jinchihe** [comment]
Sems the trainning test failed, we need to add some code to print out the pod error if the training failed.
```
{u'status': u'True', u'lastUpdateTime': u'2019-03-18T03:17:35Z', u'lastTransitionTime': u'2019-03-1
8T03:17:35Z', u'reason': u'TFJobFailed', u'message': u'TFJob mnist-test-1423 has failed because 1 Chief replica(s) failed.', u'type': u'F
ailed'}], u'replicaStatuses': {u'PS': {u'active': 1}, u'Chief': {u'failed': 1}, u'Worker': {u'active': 2}}, u'startTime': u'2019-03-18T03
:17:29Z'}
```

**Comment by jinchihe** [comment]
Seems current behavior, the pods will be delete once tfjobs finished/failed, need to set cleanPodPolicy to None to avoid deleting the pod, and then we can get logs.

**Comment by jinchihe** [comment]
Found the root cause for E2E test failing, seems that's same with https://github.com/kubeflow/examples/issues/515.

```
INFO:tensorflow:Create CheckpointSaverHook.
Traceback (most recent call last):
 File "/opt/model.py", line 233, in <module>
   tf.app.run()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
   _sys.exit(main(argv))
Extracting /tmp/data/train-images-idx3-ubyte.gz
 File "/opt/model.py", line 224, in main
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Train and evaluate
   tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
   executor.run()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
   getattr(self, task_to_run)()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 551, in run_chief
   return self._start_distributed_training()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training
   saving_listeners=saving_listeners)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 355, in train
   loss = self._train_model(input_fn, hooks, saving_listeners)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 900, in _train_model
   log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
   stop_grace_period_secs=stop_grace_period_secs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
   stop_grace_period_secs=stop_grace_period_secs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 511, in __init__
   h.begin()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 424, in begin
   self._summary_writer = SummaryWriterCache.get(self._checkpoint_dir)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer_cache.py", line 63, in get
   logdir, graph=ops.get_default_graph())
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer.py", line 352, in __init__
   filename_suffix)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
   gfile.MakeDirs(self._logdir)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 374, in recursive_create_dir
   pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
   c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, err
or message ''), response '{
"error": {
 "errors": [
  {
   "domain": "global",
   "reason": "forbidden",
   "message": "kf-v0-4-n00-user@kubeflow-ci.iam.gserviceaccount.com does not have storage.objects.get access to kubeflow-ci_temp/mnist/mo
dels/1428."
  }
 ],
 "code": 403,
 "message": "kf-v0-4-n00-user@kubeflow-ci.iam.gserviceaccount.com does not have storage.objects.get access to kubeflow-ci_temp/mnist/mode
ls/1428."
}
}

```

**Comment by jinchihe** [comment]
Roll backed some code which is used for debuging for E2E test failing.

**Comment by jlewi** [comment]
/lgtm
/approve

Any idea why the test failed on the latest run?

**Comment by jinchihe** [comment]
> /lgtm
> /approve
> 
> Any idea why the test failed on the latest run?

Seems that's caused by #515, I talked with @kunmingg, kunmingg is going to fix the problem. and seems the test infra haven't update while the last tests. Will test again.

/retest

**Comment by jinchihe** [comment]
Seems the test infra haven't update yet.

**Comment by jlewi** [comment]
See comment here:
https://github.com/kubeflow/examples/issues/515#issuecomment-476000318

**Comment by jlewi** [comment]
We have an updated cluster that is being deployed in project kubeflow-ci-deployment
https://kf-vmaster-n00.endpoints.kubeflow-ci-deployment.cloud.goog/
cluster: kf-vmaster-n00 
zone: us-east1-b

This cluster is being deployed with the new kfctl binary. I'm hoping this new binary takes care of the GCS issues.

Do you want to update the test to use the new cluster?

**Comment by jinchihe** [comment]
> We have an updated cluster that is being deployed in project kubeflow-ci-deployment
> https://kf-vmaster-n00.endpoints.kubeflow-ci-deployment.cloud.goog/
> cluster: kf-vmaster-n00
> zone: us-east1-b
> 
> This cluster is being deployed with the new kfctl binary. I'm hoping this new binary takes care of the GCS issues.
> 
> Do you want to update the test to use the new cluster?

Sounds very good! But I'm not sure how to run on the new cluster, just retest derectly and the tests will be run on new cluster?

**Comment by jlewi** [comment]
Kubeflow cluster is specified here:
https://github.com/kubeflow/examples/blob/07b485ec8c733b1b31c416577cc5314c2054ebf6/test/workflows/components/mnist.jsonnet#L20

Change this to

project: kubeflow-ci-deployment
zone: us-east1-b
cluster:  kf-vmaster-n00

**Comment by jinchihe** [comment]
Seems TFJOB still failed on new cluster, I'm going to add some debug code to find root course. Thanks.

**Comment by jlewi** [comment]
Thanks.

**Comment by jinchihe** [comment]
From the debug information, seems the root course is same as before... :-(

```
"errors": [
  {
   "domain": "global",
   "reason": "forbidden",
   "message": "kf-vmaster-n00-user@kubeflow-ci-deployment.iam.gserviceaccount.com does not have storage.objects.get access to kubeflow-ci
_temp/mnist/models/1112889025603047425/checkpoint."
  }
```

**Comment by jlewi** [comment]
Sorry for the slow reply.

This time I think its slightly different.

I think we moved the project so its still using the old project.

I created a new bucket
gs://kubeflow-ci-deployment_ci-temp

So try changing the model bucket
https://github.com/kubeflow/examples/blob/d9d61eaf5b770a637adb85599035611628b7015a/test/workflows/components/mnist.jsonnet#L27

to kubeflow-ci-deployment_ci-temp

I verified using: https://kf-vmaster-n02.endpoints.kubeflow-ci-deployment.cloud.goog
that it was working. I couldn't verify on kf-vmaster-n00 because I was using notebooks and it had an outdated version.

**Comment by jinchihe** [comment]
@jlewi Yes, That's working! Great thanks!

Please help to review since label was removed due to code changes.

**Comment by jlewi** [comment]
Woo Hoo!

@jinchihe Thank you so much for persevering!

**Pull request merged**
