### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/502)

### CODE REVIEW

**Comment by texasmichelle** [comment]
It looks like the lint issues were resolved in #493. If you rebase, that should fix the failure.

**Comment by jlewi** [comment]
Do you need to rebase off the latest changes? It looks like there are 48 files that are showing up as modified which seems like a lot for a simple typo fix.

**Comment by texasmichelle** [comment]
+1 to rebasing

**Comment by texasmichelle** [comment]
@yehiyam after a rebase, this should be good to go

**Comment by texasmichelle** [comment]
@yehiyam It would be great to get this merged. Can you rebase so that we can close this out?

**Comment by yehiyam** [comment]
Sure. I forgot about that. Im on vacation this week. I'll do it first thing next week

**Comment by jlewi** [comment]
@yehiyam sounds good thanks

**Pull request closed without merging**
