### PR TITLE
Create a end-to-end kubeflow example using seq2seq model (2/n)

### PR DESCRIPTION
**Pull request by ankushagarwal**
* Create a Dockerfile which builds the image used for this tutorial
* Update Tutorial.ipynb
  * Add a section on downloading the training data
  * Remove the Feature Extraction section
* Fix typo in setup_kubeflow_cluster.md
* Add training_the_model.md

Related to #14

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/23)

### CODE REVIEW

**Comment by jlewi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[issue_summarization_github_issues/Dockerfile, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThLqK61gHt1LBF7-A:-L6ThLqK61gHt1LBF7-B:b-lco796) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/Dockerfile#L5)):*
> ```Dockerfile
> USER root
> 
> RUN conda update -y pandas && \
> ```

Could we just add these dependencies to our existing Jupyter notebook images?

---

*[issue_summarization_github_issues/training_the_model.md, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThXdNS5REsWp5bpnd:-L6ThXdNS5REsWp5bpne:b-nqcox4) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/training_the_model.md#L5)):*
> ```Markdown
> By this point, you should have a Jupyter Notebook running at `http://127.0.0.1:8000`.
> 
> For this tutorial, we are going to use a custom docker image which contains all the source code and python library dependencies required for this tutorial. Open the Jupyter Notebook and click on `Control Panel` button on the upper right hand side of the screen. Then click on `Stop My Server`. This terminates the current instance of Jupyter Notebook.
> ```

Why do we bake source into the notebook image? Can't we just tell them to check it out from GitHub?

---

*[issue_summarization_github_issues/notebooks/Tutorial.ipynb, line 58 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThjIdyjz2xQbXnyvM:-L6ThjIdyjz2xQbXnyvN:b-84elvt) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/notebooks/Tutorial.ipynb#L58)):*
> ```
>     "!wget --directory-prefix=/mnt/github-issues-data https://storage.googleapis.com/kubeflow-examples/github-issue-summarization-data/github-issues.zip\n",
>     "\n",
>     "# Unzip the file into /mnt/github-issues-data directory\n",
> ```

Do we need to store the data on a POSIX filesystem? Could we use object storage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Comment by ankushagarwal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[issue_summarization_github_issues/Dockerfile, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThLqK61gHt1LBF7-A:-L6UHwL1w5fv-sFwxgG7:b-896fix) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/Dockerfile#L5)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Could we just add these dependencies to our existing Jupyter notebook images?
</blockquote></details>

Done.

---

*[issue_summarization_github_issues/training_the_model.md, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThXdNS5REsWp5bpnd:-L6UHy-XulDbnhvoXZYO:b-896fix) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/training_the_model.md#L5)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why do we bake source into the notebook image? Can't we just tell them to check it out from GitHub?
</blockquote></details>

Done.

---

*[issue_summarization_github_issues/notebooks/Tutorial.ipynb, line 58 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThjIdyjz2xQbXnyvM:-L6UJNQZrdTzO03oXotl:b2tkudk) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/notebooks/Tutorial.ipynb#L58)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Do we need to store the data on a POSIX filesystem? Could we use object storage?
</blockquote></details>

Object storage is sufficient, but I am not familiar with how to get access to that inside the pod.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Comment by ankushagarwal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[issue_summarization_github_issues/training_the_model.md, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThXdNS5REsWp5bpnd:-L6UJtoBEPHJUto4vjEK:b-7y5r52) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/training_the_model.md#L5)):*
<details><summary><i>Previously, ankushagarwal (Ankush Agarwal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Created https://github.com/kubeflow/kubeflow/pull/315

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Comment by jlewi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[issue_summarization_github_issues/Dockerfile, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThLqK61gHt1LBF7-A:-L6XnRVD0FZd0S5sO1rp:bdje2sp) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/Dockerfile#L5)):*
<details><summary><i>Previously, ankushagarwal (Ankush Agarwal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So do we still need this file? 

---

*[issue_summarization_github_issues/notebooks/Tutorial.ipynb, line 58 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThjIdyjz2xQbXnyvM:-L6Xnq79tZ2fo4Hq3q_b:bwqcxxg) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/notebooks/Tutorial.ipynb#L58)):*
<details><summary><i>Previously, ankushagarwal (Ankush Agarwal) wrote…</i></summary><blockquote>

Object storage is sufficient, but I am not familiar with how to get access to that inside the pod.
</blockquote></details>

The recommendation for GKE is to use a service account and then create a kubernetes secret using the private key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Comment by ankushagarwal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[issue_summarization_github_issues/notebooks/Tutorial.ipynb, line 58 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThjIdyjz2xQbXnyvM:-L6Y5v6hYzHCwMbY1he_:b-iypmbn) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/notebooks/Tutorial.ipynb#L58)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

The recommendation for GKE is to use a service account and then create a kubernetes secret using the private key.
</blockquote></details>

Discussed offline

---

*[issue_summarization_github_issues/Dockerfile, line 5 at r2](https://reviewable.io:443/reviews/kubeflow/examples/23#-L6ThLqK61gHt1LBF7-A:-L6XptmM3xMj0u1UmfpH:bhofej8) ([raw file](https://github.com/kubeflow/examples/blob/37782ea7d5bf2192754d5696aa9d281ab8328928/issue_summarization_github_issues/Dockerfile#L5)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

So do we still need this file? 
</blockquote></details>

Deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Comment by jlewi** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/examples/23)*

**Pull request merged**
