### PR TITLE
initial commit of example showing remote (out of cluster) pipeline deployment

### PR DESCRIPTION
**Pull request by amygdala**
A PR into the new 'cookbook' branch, where several of us are going to collaborate on small notebook-based examples that show how to do specific things.  This content is not ready to be pulled into master.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/525)

### CODE REVIEW

**Comment by jlewi** [comment]
The idea of cook books sounds great. Thanks for leading this!

**Comment by amygdala** [comment]
Michelle, when you get a chance, would you be up for merging this PR?— into the **cookbook branch**, not master. The intent is that this branch will support some collaborative work amongst a few of us.

(It will be a while before this branch is ready to be pulled into master-- these are just some preliminary additions).

**Pull request merged**
