### PR TITLE
Bump fairing commit to latest on master to fix examples

### PR DESCRIPTION
**Pull request by iancoffey**
Fixes kubeflow/examples#792.

Bumps fairing commit to latest on master to fix examples.

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks!

/lgtm
/approve

**Comment by iancoffey** [comment]
CI is red, I will sort out why.

**Comment by iancoffey** [comment]
[AFAICT](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-examples-gis-6192-4669?tab=timeline&nodeId=kubeflow-periodic-examples-gis-6192-4669-870297017), this is red due to `fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-periodic-examples-gis-6192-4669/src/kubeflow/examples': No space left on device`. 

cc @jinchihe @jlewi Does that sound right? Im not sure how we allocate disk for prow jobs, so not sure how to approach this.

**Comment by jinchihe** [comment]
We are going to resolve now, please waiting for some hours, thanks.

**Comment by jlewi** [comment]
The tests failed because they were unable to get credentials for the auto-deployed cluster.

```
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-deployment/global/deplo
yments/kf-v1-0509-b12/resources/kf-v1-0509-b12?alt=json returned "The object 'projects/kubeflow-ci-deployment/global/deployments/kf-v1-0509-b12/resources/kf-
v1-0509-b12' is not found.">
```

This looks like an old auto-deployed cluster which appears to not be functional; likely because of quota issues.

There is a fresh cluster kf-v1-0513-ba9 that has been created since the last test run but this cluster doesn't have an accessible endpoint.

**Comment by iancoffey** [comment]
> E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kubeflow-kf-ci-v1-user\" not found","reason":"NotFound","details":{"name":"kubeflow-kf-ci-v1-user","kind":"namespaces"},"code":404}

Does the `kubeflow-kf-ci-v1-user` NS need to be manually created?

**Comment by jlewi** [comment]
Namespace shouldn't need to be created manually. We don't have healthy auto-deployed clusters right now because of kubeflow/testing#660
We are tracking fixing auto deployments in kubeflow/testing#664. We will need to wait for kubeflow/testing#664 to be fixed before the tests will be able to pass.

**Comment by jlewi** [comment]
The CI clusters should be back up and healthy.
/test all

**Comment by iancoffey** [comment]
> E     AttributeError: 'NoneType' object has no attribute 'download_to_filename'

So the retrieved blob is nil/404, for this last test

**Comment by jlewi** [comment]
@iancoffey it looks like the notebook is erroring out. Which is why the notebook doesn't exist.
The test fires off a K8s job to run the notebook and that job is what's failing. So this likely indicates the notebook isn't working. To debug further you can dig into the logs of that k8s job.

If you look at the instructions on 
https://github.com/kubeflow/testing

You can open a PR to get viewer permission to the logs and then use stackdriver to fetch the K8s job logs.

**Comment by iancoffey** [comment]
Requested permissions in https://github.com/kubeflow/internal-acls/pull/245

**Comment by jlewi** [comment]
@iancoffey You could also use the pytest markers to mark the failing tests as expected failures. That way we could unblock this PR which at least fixes some of the tests. As well as other PRs potentially blocked by the failing tests.

**Comment by jlewi** [comment]
@iancoffey I just sync'd the groups so you should me a member of ci-viewer@kubeflow.org

**Comment by iancoffey** [comment]
@jlewi Thank you, I do see the KF workspaces now but sadly all things inside stackdriver show I lack perms 🤔 

> You do not have sufficient permissions to view this page
> There was an error while loading /monitoring?project=kubeflow-ci-deployment&authuser=1.

> Check that the IDs are valid and you have permissions to access them. Learn more

I will try to skip these tests in the meanwhile.

**Comment by jlewi** [comment]
> Thank you, I do see the KF workspaces now but sadly all things inside stackdriver show I lack perms

What do you mean by KF worksapces?

What did you do to try access stackdriver? Which project did you look at? 

If you are still unable to view the logs please open up an issue.

I confirmed ci-viewer has access log viewer on project kubeflow-ci-deployment

[kubeflow-ci-deployment.yaml.txt](https://github.com/kubeflow/examples/files/4644726/kubeflow-ci-deployment.yaml.txt)

Here's a list of members of ci-viewer
[ci-viewer.txt](https://github.com/kubeflow/examples/files/4644736/ci-viewer.txt)

So you are present.

Is icoffey@vmware.com a Google account?

**Comment by iancoffey** [comment]
> What do you mean by KF worksapces?

GCP Monitoring Workspaces - looks like there are two, `kubeflow-ci` and `kubeflow-ci-deployments`. I was just mentioning they are visible in the console so I must have permissions.

> What did you do to try access stackdriver? Which project did you look at?

I tried to access stackdriver via the google console as icoffey@vmware.com - I didn't see any instructions on the testing docs on the exact URIs. Ive never used stackdriver before so Im just guessing as the docs don't specify.

**Comment by iancoffey** [comment]
@jlewi This is green now and I opened https://github.com/kubeflow/examples/issues/797 to get the test fixed/enabled, to unblock merges.

**Pull request merged**
