### PR TITLE
Example of converting Store Sales Forecast Kaggle notebook to a Kubeflow pipeline

### PR DESCRIPTION
**Pull request by NeoKish**
/assign @kimwnasptd
/assign @js-ts
/assign @jinchihe

### CODE REVIEW

**Comment by jbottum** [comment]
@NeoKish thanks for this documentation and tutorial update.    A few questions.   Does this run on KF 1.6 ?   This tutorial uses Kale.   Does Kale require Rok ?

**Comment by NeoKish** [comment]
@jbottum, thanks for the comment. So I am using Arrikto's KFaaS. The Kubeflow version is 1.4 based on the latest release. Yes Kale does have dependency on Rok.

**Comment by kimwnasptd** [comment]
Took a look at the code of the example

/lgtm

**Comment by akgraner** [comment]
Thank you for your contribution!

/approve

**Pull request merged**
