### PR TITLE
Fix broken url for example file in simple_pipeline demos

### PR DESCRIPTION
**Pull request by janeman98**
In https://github.com/kubeflow/examples/tree/master/demos/simple_pipeline,

3. Perform hyperparameter tuning
In order to determine parameters that result in higher accuracy, use Katib to execute a Study, which defines a search space for performing training with a range of different parameters.

Create a Study by applying an example file to the cluster:

The "example file" is pointing to a broken link at https://github.com/kubeflow/katib/blob/master/examples/gpu-example.yaml

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/660)

### CODE REVIEW

**Comment by jinchihe** [comment]
ok-to-test

**Comment by jinchihe** [comment]
@janeman98 Thanks for your contribution recently.

Could you please apply memeber of kubeflow following the [guide](https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org)? after that, you PR will be tested automatically.

**Comment by janeman98** [comment]
Thanks @jinchihe !
As per your feedback above, I have created a PR to apply for kubeflow membership : https://github.com/kubeflow/internal-acls/pull/178

**Pull request merged**
