### PR TITLE
Enhanced readme for MNIST example to include working S3 documentation (#466)

### PR DESCRIPTION
**Pull request by mnmainguy**
- Modified the S3 training portion of the MNIST example to set necessary env variables
- Modified the S3 tensor portion of the MNIST example to use correct env variables from S3 training
- Added instructions for S3 serving of MNIST example 
- Added missing modelName in mnist-deploy-aws params

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/543)

### CODE REVIEW

**Comment by jlewi** [comment]
@jeffwan This looks good to me but it might be good to have someone with AWS review it.

**Comment by Jeffwan** [comment]
Thanks for ping. @jlewi LGTM too

**Comment by texasmichelle** [comment]
Looks like it's good to go after a rebase

**Comment by texasmichelle** [comment]
@mnmainguy it would be great to get this merged. Can you rebase so that we can close this out?

**Comment by mnmainguy** [comment]
@texasmichelle I think this needs significant revision because the readme has switched to using kustomize vs ksonnet. If there's still interest, I can revise it over the weekend with the rebase. Does that work?

**Comment by jlewi** [comment]
@mnmainguy yes I think it would be great to update this to work with kustomize.
I believe @jinchihe updated the mnist example to work with kustomize since ksonnet is deprecated.
So it would be great to ensure we have up to date docs with kustomize for AWS/S3.

Apologies for the churn.

/assign @Jeffwan 
/assign @jinchihe

**Comment by jinchihe** [comment]
@mnmainguy Thanks for the enhancement! Yes, that's very expected if you can rebase and update with the README, I saw the PR is going to add the s3 part, I'm glad if any need helping with kustomize.

**Comment by jlewi** [comment]
@mnmainguy Any interest in revising this PR?

**Comment by mnmainguy** [comment]
@jlewi Yes, I'd be happy to but I'm overcommitted on other projects for the next week or so. I can have it done by 8/19 if that works.

**Comment by jlewi** [comment]
8/19 works thank you very much!

**Comment by mnmainguy** [comment]
@jlewi @jinchihe @Jeffwan Thanks for your patience. Changes to serve from S3 using Kustomize are up and ready to review. I found a bug in the way Kustomize was set for the AWS secrets in S3 Training and Monitoring so I fixed that as well (Kustomize adds a suffix to secret names when they are generated but the pods were just looking for the string "aws-creds").

**Pull request merged**
