### PR TITLE
Adding simple pipeline example

### PR DESCRIPTION
**Pull request by zanedurante**
This PR is  an extension of https://github.com/kubeflow/examples/pull/592  @richardsliu.   @texasmichelle the changes you requested have been made.  Issue: kubeflow/website#891

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/598)

### CODE REVIEW

**Comment by zanedurante** [comment]
PR for issue kubeflow/website#891.   Created at doc sprint @sarahmaddox

**Comment by sarahmaddox** [comment]
Thanks @zanedurante! Please would you or @richardsliu add the **doc-sprint** label to this PR, so we can track it for the doc sprint results. (I don't have access to add labels in the kubeflow/examples repo.)

**Comment by richardsliu** [comment]
@sarahmaddox Done

**Comment by sarahmaddox** [comment]
Thanks!

**Comment by jinchihe** [comment]
@zanedurante Thanks for the great contribution! 

/lgtm
/approve

**Pull request merged**
