### PR TITLE
Fix performance of dataflow preprocessing job.

### LINKED ISSUE #299: [code_search] preprocess_github_dataset should print out the Dataflow job that was submitted
When you run `preprocess_github_dataset` there is no indication that a Dataflow job was submitted.
See output below. We should print out information indicating a Dataflow job was submitted.

Otherwise its not clear to users what happened (e.g. #297)

Here's the command I ran

```
 python2 -m code_search.dataflow.cli.preprocess_github_dataset --runner=DataflowRunner --project=code-search-demo --target_dataset=code_search --data_dir=gs://code-search-demo/20181103/data --job_name=submit-preprocess-job --temp_location=gs://code-search-demo/20181103/dataflow/temp --staging_location=gs://code-search-demo/20181103/dataflow/staging --worker_machine_type=n1-highcpu-32 --num_workers=16
```

Here's the output
```
running sdist
running egg_info
creating code_search.egg-info
writing requirements to code_search.egg-info/requires.txt
writing code_search.egg-info/PKG-INFO
writing top-level names to code_search.egg-info/top_level.txt
writing dependency_links to code_search.egg-info/dependency_links.txt
writing manifest file 'code_search.egg-info/SOURCES.txt'
reading manifest file 'code_search.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'code_search.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating code-search-0.1.dev0
creating code-search-0.1.dev0/code_search
creating code-search-0.1.dev0/code_search.egg-info
creating code-search-0.1.dev0/code_search/dataflow
creating code-search-0.1.dev0/code_search/dataflow/cli
creating code-search-0.1.dev0/code_search/dataflow/do_fns
creating code-search-0.1.dev0/code_search/dataflow/transforms
creating code-search-0.1.dev0/code_search/nmslib
creating code-search-0.1.dev0/code_search/nmslib/cli
creating code-search-0.1.dev0/code_search/t2t
copying files to code-search-0.1.dev0...
copying MANIFEST.in -> code-search-0.1.dev0
copying requirements.txt -> code-search-0.1.dev0
copying setup.py -> code-search-0.1.dev0
copying code_search/__init__.py -> code-search-0.1.dev0/code_search
copying code_search.egg-info/PKG-INFO -> code-search-0.1.dev0/code_search.egg-info
copying code_search.egg-info/SOURCES.txt -> code-search-0.1.dev0/code_search.egg-info
copying code_search.egg-info/dependency_links.txt -> code-search-0.1.dev0/code_search.egg-info
copying code_search.egg-info/requires.txt -> code-search-0.1.dev0/code_search.egg-info
copying code_search.egg-info/top_level.txt -> code-search-0.1.dev0/code_search.egg-info
copying code_search/dataflow/__init__.py -> code-search-0.1.dev0/code_search/dataflow
copying code_search/dataflow/utils.py -> code-search-0.1.dev0/code_search/dataflow
copying code_search/dataflow/cli/__init__.py -> code-search-0.1.dev0/code_search/dataflow/cli
copying code_search/dataflow/cli/arguments.py -> code-search-0.1.dev0/code_search/dataflow/cli
copying code_search/dataflow/cli/create_function_embeddings.py -> code-search-0.1.dev0/code_search/dataflow/cli
copying code_search/dataflow/cli/preprocess_github_dataset.py -> code-search-0.1.dev0/code_search/dataflow/cli
copying code_search/dataflow/do_fns/__init__.py -> code-search-0.1.dev0/code_search/dataflow/do_fns
copying code_search/dataflow/do_fns/dict_to_csv.py -> code-search-0.1.dev0/code_search/dataflow/do_fns
copying code_search/dataflow/do_fns/function_embeddings.py -> code-search-0.1.dev0/code_search/dataflow/do_fns
copying code_search/dataflow/do_fns/github_dataset.py -> code-search-0.1.dev0/code_search/dataflow/do_fns
copying code_search/dataflow/do_fns/prediction_do_fn.py -> code-search-0.1.dev0/code_search/dataflow/do_fns
copying code_search/dataflow/transforms/__init__.py -> code-search-0.1.dev0/code_search/dataflow/transforms
copying code_search/dataflow/transforms/bigquery.py -> code-search-0.1.dev0/code_search/dataflow/transforms
copying code_search/dataflow/transforms/function_embeddings.py -> code-search-0.1.dev0/code_search/dataflow/transforms
copying code_search/dataflow/transforms/github_bigquery.py -> code-search-0.1.dev0/code_search/dataflow/transforms
copying code_search/dataflow/transforms/github_dataset.py -> code-search-0.1.dev0/code_search/dataflow/transforms
copying code_search/nmslib/__init__.py -> code-search-0.1.dev0/code_search/nmslib
copying code_search/nmslib/search_engine.py -> code-search-0.1.dev0/code_search/nmslib
copying code_search/nmslib/search_server.py -> code-search-0.1.dev0/code_search/nmslib
copying code_search/nmslib/cli/__init__.py -> code-search-0.1.dev0/code_search/nmslib/cli
copying code_search/nmslib/cli/arguments.py -> code-search-0.1.dev0/code_search/nmslib/cli
copying code_search/nmslib/cli/create_search_index.py -> code-search-0.1.dev0/code_search/nmslib/cli
copying code_search/nmslib/cli/embed_query_test.py -> code-search-0.1.dev0/code_search/nmslib/cli
copying code_search/nmslib/cli/start_search_server.py -> code-search-0.1.dev0/code_search/nmslib/cli
copying code_search/t2t/__init__.py -> code-search-0.1.dev0/code_search/t2t
copying code_search/t2t/function_docstring.py -> code-search-0.1.dev0/code_search/t2t
copying code_search/t2t/function_docstring_extended.py -> code-search-0.1.dev0/code_search/t2t
copying code_search/t2t/query.py -> code-search-0.1.dev0/code_search/t2t
copying code_search/t2t/similarity_transformer.py -> code-search-0.1.dev0/code_search/t2t
copying code_search/t2t/similarity_transformer_test.py -> code-search-0.1.dev0/code_search/t2t
Writing code-search-0.1.dev0/setup.cfg
Creating tar archive
removing 'code-search-0.1.dev0' (and everything under it)
Collecting apache-beam==2.6.0
  Downloading https://files.pythonhosted.org/packages/d6/7d/1294f67c4132e4385edbc6c9efb4f83a7262fa45321e3299c56aaf238de1/apache-beam-2.6.0.zip (2.3MB)
    100% |████████████████████████████████| 2.3MB 5.7MB/s 
  Saved /tmp/tmpoEwVKU/apache-beam-2.6.0.zip
Successfully downloaded apache-beam
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting apache-beam==2.6.0
  Using cached https://files.pythonhosted.org/packages/26/44/38642c061f1f1d1ffc166e452f74ec1cc5d14be5afccc0b970af5be34828/apache_beam-2.6.0-cp27-cp27mu-manylinux1_x86_64.whl
  Saved /tmp/tmpoEwVKU/apache_beam-2.6.0-cp27-cp27mu-manylinux1_x86_64.whl
Successfully downloaded apache-beam
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

### LINKED ISSUE #300: [code_search] Dataflow job to preprocess the dataset is really slow
I'm running the Dataflow job to preprocess the data (produce CSV).

Dataflow is indicating only 90 elements/s being processed and indicating days of wall time. This seems awfully slow. 

Based on the graph it seems like the big bottle neck is the tokenize code step.

### PR DESCRIPTION
**Pull request by jlewi**
* Fix #300; Dataflow job for preprocessing is really slow.

  * The problem is we are loading the spacy tokenization model on every
    invocation of the tokenization function and this is really expensive.
  * We should be doing this once per module import.

* After fixing this issue; the job completed in approximately 20 minutes using
  5 workers.

  * We can process all 1.3 million records in ~ 20 minutes (elapsed time) using 5 32 CPU workers and about 1 hour of CPU time altogether.

* Add options to the Dataflow job to read from files as opposed to BigQuery
  and to skip BigQuery writes. This is useful for testing.

* Add a "unittest" that verifies the Dataflow preprocessing job can run
  successfully using the DirectRunner.

* Update the Docker image and a ksonnet component for a K8s job that
  can be used to submit the Dataflow job.

* Fix #299; Add logging to the Dataflow preprocessing job to indicate that
  a Dataflow job was submitted.

* Add an option to the preprocessing Dataflow job to read an entire
  BigQuery table as the input rather than running a query to get the input.
  This is useful in the case where the user wants to run a different
  query to select the repo paths and contents to process and write them
  to some table to be processed by the Dataflow job.

/assign @activatedgeek @richardsliu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/302)

### CODE REVIEW

**Comment by activatedgeek** [comment]
/lgtm

Interesting! Was shifting the module import once per module the only reason for improving the speed? Or this also included a shift to reading from files?

**Comment by jlewi** [comment]
@activatedgeek It was just the module import; I was able to run the full Dataflow job using a BigQuery as input in elapsed time of ~ 20 minutes using 5 workers.

**Comment by cwbeitel** [comment]
@jlewi Nice.

**Pull request merged**
