### PR TITLE
Added a README to the pipelines samples dir

### PR DESCRIPTION
**Pull request by sarahmaddox**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/575)

### CODE REVIEW

**Comment by jinchihe** [comment]
@sarahmaddox May I suggest adding some description for the pipeline examples in the [examples Readme](https://github.com/kubeflow/examples/blob/master/README.md) as other sections/link in thi page. thanks.

**Comment by sarahmaddox** [comment]
> @sarahmaddox May I suggest adding some description for the pipeline examples in the [examples Readme](https://github.com/kubeflow/examples/blob/master/README.md) as other sections/link in thi page. thanks.

@jinchihe That's a good idea. I've already sent the following PR to add a README in the pipelines section: https://github.com/kubeflow/examples/pull/575

If you or another community member want to add to the examples README that you mention, that'd be great.

**Comment by jinchihe** [comment]
> > @sarahmaddox May I suggest adding some description for the pipeline examples in the [examples Readme](https://github.com/kubeflow/examples/blob/master/README.md) as other sections/link in thi page. thanks.
> 
> @jinchihe That's a good idea. I've already sent the following PR to add a README in the pipelines section: #575
> 
> If you or another community member want to add to the examples README that you mention, that'd be great.

OK, Will send another PR to update later. Thanks.

**Pull request merged**
