### PR TITLE
Chinese multiperson voice recognition-transfer learning

### PR DESCRIPTION
**Pull request by bebe424**

### CODE REVIEW

**Comment by bebe424** [comment]
@google-oss-robot   I signed it!

**Comment by bebe424** [comment]
@googlebot I signed it!

**Comment by bebe424** [comment]
@jinchihe Hello, I’m a student who published transfer learning before. Because of some problems, I re-published it. The previous problem was also fixed. Please help me review the project. Thank you

**Comment by jinchihe** [comment]
@bebe424 Thanks for the contribution! Looks good now.

/lgtm
/approve

**Comment by 482170765** [comment]
@jinchihe We are the same team with bebe424.  Recently, we have raised several issues with regard to kubwflow enhancements such as bagging, swarm, and random forest etc.  They are issues 1036, 1039, 1041, 1042, 1043, 1045, and 1046.  Moreover, they are integrated with Node-red, a graphical interface that allows users to triger kubbeflow pipeline execution.   Can you help review these issues and see if they are proper to be published within the examples site?

**Comment by 482170765** [comment]
@google-oss-robot @jinchihe We are the same team with bebe424.  Recently, we have raised several issues with regard to kubwflow enhancements such as bagging, swarm, and random forest etc.  They are issues 1036, 1039, 1041, 1042, 1043, 1045, and 1046.  Moreover, they are integrated with Node-red, a graphical interface that allows users to triger kubbeflow pipeline execution.   Can you help review these issues and see if they are proper to be published within the examples site?

**Pull request merged**
