### PR TITLE
Transfer-Learning - chinese multiperson voice recognition

### PR DESCRIPTION
**Pull request by sports75482**
Transfer-Learning-main - chinese multiperson voice recognition
[Chinese-multiperson-voice-recognition-using-transfer-learning-main.zip](https://github.com/kubeflow/examples/files/6892456/Chinese-multiperson-voice-recognition-using-transfer-learning-main.zip)

### CODE REVIEW

**Comment by sports75482** [comment]
@googlebot I signed it!

google-cla[bot] ***@***.***> 於 2021年6月28日 週一 上午11:33寫道：

**Comment by sports75482** [comment]
@jinchihe Hello, I have uploaded a file here, can you help me review it, thank you

**Comment by sports75482** [comment]
@jinchihe Dear Sir, we have pulled a suite of code of transfer learning applications on multi-person Chinese voice recognition.  We wish to contribute to the Kubeflow community.  Eventually, we wish to generate a pipeline specifically for transfer learning for machine learning developer.  Please help us in this respect.

**Comment by jinchihe** [comment]
@sports75482 Thanks for the contribution and sorry for response later.

Would you please make a directory for the example and add some description for this? I just also the code diff that includes a Compressed file.

**Comment by sports75482** [comment]
@jinchihe Thank you for your reply. The README file in the file I created describes my project.

**Comment by jinchihe** [comment]
@sports75482 would you please untar your projects, I just see the two file in code changes.

image

**Comment by sports75482** [comment]
> Transfer-Learning-main - chinese multiperson voice recognition
> [Chinese-multiperson-voice-recognition-using-transfer-learning-main.zip](https://github.com/kubeflow/examples/files/6892456/Chinese-multiperson-voice-recognition-using-transfer-learning-main.zip)

**Pull request closed without merging**
