### PR TITLE
Update ci tests for mnist example

### PR DESCRIPTION
**Pull request by jinchihe**
fixes: #677

The PR is going to:

1. Change tfjob_test.py to use pytest to support better reporting of test results

2. Change deploy_test.py change to use pytest

3. Replace the ksonnet workflow with the use of python to define the workflow

4. Removed GOOGLE_APPLICATION_CREDENTIALS setting and using work identity.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/684)

### CODE REVIEW

**Comment by jinchihe** [comment]
That's strange.. Cannot get the trainning data from tensorflow, caused by network issue?
```
Traceback (most recent call last):
  File "/opt/model.py", line 204, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/opt/model.py", line 147, in main
    mnist = tf.contrib.learn.datasets.DATASETS['mnist'](TF_DATA_DIR)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 300, in load_mnist
    return read_data_sets(train_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 260, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 219, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 172, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 200, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 99] Cannot assign requested address
```

**Comment by jinchihe** [comment]
Another problem, seems no permission to upload data to gs ...
```
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, error message ''), response '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
'
	 when initiating an upload to gs://kubeflow-ci-deployment_ci-temp/mnist/models/1201767042638680064/
```

**Comment by jinchihe** [comment]
Hello @jlewi , the changes is ready for reviewing, thanks!
/assign @jlewi

**Comment by jlewi** [comment]
Thank you so much @jinchihe !

**Comment by jinchihe** [comment]
Hello @jlewi Thanks for your comments. Updated as below:

- Updated from `gcr.io/kubeflow-ci` to `gcr.io/kubeflow-examples`.
- Point to a well defined newTag which is includes new model.py (the old one is include out-of-date model.py)
- For the testing, we used the `kustomize edit set image` to update to use the image that's built by this current PR in build steps.

**Pull request merged**
