### PR TITLE
[docs]: enhance documentation for chosen namespace

### PR DESCRIPTION
**Pull request by travishen**
The web-ui pod is deploy on namespace `kubeflow`.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/555)

### CODE REVIEW

**Comment by travishen** [comment]
I signed it!

**Comment by jinchihe** [comment]
@travishen In fact, we have description in the `Preparing your Kubernetes Cluster` section in the README file as `In the following instructions we will install our required components to a single namespace. For these instructions we will assume the chosen namespace is kubeflow`. so all commands in the README file omit the `-n kubeflow`. do you think is that need to clear this? if so, personally I suggest to add more clear descrition to remind user to configure k8s content to set `kubeflow` as current namespace. Thanks.

**Comment by travishen** [comment]
@jinchihe Thanks for the remind. I've updated it by:
* Add command to set the namespace preference
* Omit the `-n kubeflow` in two commands

**Comment by jinchihe** [comment]
> @jinchihe Thanks for the remind. I've updated it by:
> 
>     * Add command to set the namespace preference
> 
>     * Omit the `-n kubeflow` in two commands

Great! Thanks!

**Comment by travishen** [comment]
Thanks for the review!

**Pull request merged**
