### PR TITLE
Inception Export trained Checkpionts example

### PR DESCRIPTION
**Pull request by yupbank**
address https://github.com/kubeflow/kubeflow/issues/229

The goal is actually moving the whole piece  https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/README.md into here

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/examples/4)

### CODE REVIEW

**Comment by jlewi** [comment]
Per comment in that issue; https://github.com/kubeflow/kubeflow/issues/229#issuecomment-364619248

Can you provide more detail about the end goal? e.g. what will a final complete example look like?

**Comment by jlewi** [comment]
@yupbank Ping?

**Comment by yupbank** [comment]
Thanks... not it's not blocking, i will pick it up

**Comment by jlewi** [comment]
Going to close this as stale.

**Pull request closed without merging**
