### PR TITLE
Add js-ts as an approver

### PR DESCRIPTION
**Pull request by js-ts**
Thanks @jinchihe for the opportunity

### CODE REVIEW

**Comment by jinchihe** [comment]
Welcome! Seems you are not member of Kubeflow org? would you please add kubeflow org firstly? Thanks. @js-ts

**Comment by js-ts** [comment]
@jinchihe my [PR](https://github.com/kubeflow/examples/pull/899) to become a Kubeflow member got approved

**Comment by jinchihe** [comment]
/lgtm
/approve

Thanks @js-ts welcome contribution as maintainer!

**Pull request merged**
